[connections.gsheets]
type = "service_account"
project_id = "hazel-phoenix-479803-v8"
private_key_id = "310749d8b056ed91dc14313cf9b98ab80ee80ba3"
client_email = "trading-journal@hazel-phoenix-479803-v8.iam.gserviceaccount.com"
client_id = "108368847214100992536"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/trading-journal%40hazel-phoenix-479803-v8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCL/M+UWqtUfesw
QxK/v7eozsM5N0jpK3UXtoXT+c5SeywrLjM/XKCqX5hOcvGNFZDQqJzRhUvaYx0B
1xD/Fm0GA2hkMVbY/mkvg5BCbF/Mv3hLotKdLhIYFVmdIFxJQ5UJJACecaeF1XD3
hPPxJiitjHDXpL2C/SlsFRNECqnvlZBscSiUJvKqHIWHuQCoXyrGtzB3MSMtTW5p
UYrkKz0XQX+sZKKAOzovW8uvlaGUW3kmv2wiGJCTmbjd2C3YD/CObtDsF9h1YS8/
NEBNu+iPungYSa7WGTray45D4NhJ4qtC3VnYZfvwvrBAxG5hpnmP771GozXl4GAR
R3sfAisxAgMBAAECggEAD35ppL5E0ocVz/uKgJPaAmpxF9z3OkyDqx5Z8VhnpkAp
BzX3uNp6E2VdfIhTFSYXB0s0QSnnV3prGFwrDsq3AiiAJj/CQKXm8zn07m8jisxB
5qA0vq4d1VHOn3oYkMjUvuRf16mVbLYPKOwrmkwaijveNPXwPkZiLmrmPRyPirtp
jaxNWQWh9rOeY8jv8cYQSIEGbKgRosw7tO02xqjDSGKeeFwAu//9vVy+Q6b78Hvs
Cdt8Kt6GMndzvoI6O6cTvpG7xuxOdIVh3+bG0i+7i+a53gpDBK4XfwGyahMoS4cZ
g16n/3g4OhHYIiPfbDZb5Ntvr9diERT1RRkj5M62aQKBgQDAa28q/WTbdXrLDPFn
3kfOmLLCT4zWtwrSNK0R+W4G4ENNWrO16VrliHDSqFXwJhxwd6oulj6PVmYDywo4
zYVK/PRLTdsNZt943CW5E7fGZD5sZ0O67JscpzB92XDLgxmxO2fcr0kdl2S75FyX
1zUfqfKV2EJmMU8mtEm8qZ1peQKBgQC6PjObYmSwY/y7WiK4Cb7qIQcMg/6Dns2K
K3pdiwmEQmegF+i6OgEhlZFUSkPpZ+8IjO+7cwZ1Q563VoX8oiKE71zETR5hLQOe
psKtJmH38j0vLqE783D5W2DQ+fPynjqIrcvYkrSLk9MQJmzbMSfRyfRvZ72cwdUB
KFr06aKZeQKBgQC+189ia//kShiH20ZzJltB5OEnJ48gRltNMUGWWjVuTG90AUnM
Wq30ieaciKjzjlkWkxkPK6TQtXhourBgtbZFsaz6IzXnjOiIDpC7h3r2IeZnzeO3
OYR+XrQRnd/peRW6WpkgoBl8Z/NZB51uW9wskvoudFcm1DEUyit4GyIswQKBgB5X
hebZt9e44nLPc3qSM+VG7jQOyQc+dvP8s1nMDgfbHbDKVGMKkiabjGq0Eq5S/XFi
LKhYTAQMuS3bTcbjz0XjDTT572obgEx3lJ3K9AkGEQu/yArRVWV6iqJhJmovdw/P
aLdm5z0aHzexWui28GrQQR9pQk3okkA3B+KAsbnZAoGBAKs6Mx3Vjz000NlYBzlF
+jXxGfISeXXkr8O9D+QTe5d4g8cJtT1a6EUx0OaY0Q5m+mc9pTcKaUMpQ6OGqZz3
wxhpemCmOHOsMivt2tbQpK1WpRlNhZSvjznc1A9NEmX3Cyv4aZCgDgz6DDLR+6il
eQAkjGrJgHW3xM7woVvxsm0A
-----END PRIVATE KEY-----
"""
